spring:
  application:
    name: customer-services
  datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/RBI_Database
      username: dreamsol
      password: dreamsol
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081
